### ISSUE TITLE
Koppeling kunnen maken met RX.Mission testomgeving (postman)

### ISSUE THREAD

**Issue by joostvanderborg** [GemeenteNijmegen/webformulieren-submissionstorage#302]
De beschikbare credentials geven nog foutmeldingen. Zorgen dat de benodigde endpoints (zaak, zaaktype, catalogus, informatieobject) beschikbaar zijn voor ons.

**Comment by WietekeNijmegen** [comment]
Koppeling in postman gelukt. Prod en preprod.
We moeten hier wel nog een keer nieuwe credentials voor aanvragen die veilig gestuurd worden. Deze zijn nu via projectleiding per mail binnen gekomen.

**Comment by joostvanderborg** [comment]
Issue aangemaakt voor roteren secrets: https://github.com/GemeenteNijmegen/webformulieren-submissionstorage/issues/309
