### ISSUE TITLE
Productiekoppeling activeren

### ISSUE THREAD

**Issue by joostvanderborg** [GemeenteNijmegen/webformulieren-submissionstorage#307]
Productiekoppeling in RX.Mission actief maken. Controleer hierbij of testinzending in productieomgeving voor 1-12 een issue is?

Kan pas na 16 december.
![Image](https://github.com/user-attachments/assets/1dc08cd5-04d7-48f2-8c0b-e47b82328051)

- [x] AppID's prod formulieren omzetten
- [x] Prod config in submissionstorage inrichten
- [x] Feature flag omzetten

**Comment by WietekeNijmegen** [comment]
De zaaktypen en dergelijke zijn nog niet te vinden op productie. De producten op prod hebben we van Johannes per mail gekregen. [productennijmegenprod.json](https://github.com/user-attachments/files/18011068/productennijmegenprod.json)

Om alles live te kunnen zetten moeten we:
- de prod config maken in RxMissionZgwConfiguration.ts met de zaaktype etc uit de catalogi
- de appId's in de debetreffende formulieren omzetten van DMS naar de Rxx waardes en BDI een seintje geven
- de feature flag aanzetten in de submissionstorage config:    enableRxMissionZwgHandler: true,

**Comment by joostvanderborg** [comment]
taken uit dit issue overgenomen in eigen issues:
- [ ] [Contactformulier live](https://github.com/GemeenteNijmegen/webformulieren-submissionstorage/issues/395)  (bestond al)
- [ ] [Bouwformulier live](https://github.com/GemeenteNijmegen/webformulieren-submissionstorage/issues/415)

De productiekoppeling is actief, ik sluit dit issue.
