### ISSUE TITLE
Formulier PDF informatieObjecttype Verzoek

### ISSUE THREAD

**Issue by WietekeNijmegen** [GemeenteNijmegen/webformulieren-submissionstorage#379]
Nu hebben alle documenten het informatieobjecttype Bijlage Verzoek. Dit moet alleen zo zijn voor de echte bijlages. De PDF met het hele formulier erin moet informatieobjecttype Verzoek krijgen.

**Comment by joostvanderborg** [comment]
Als configuratie specifieke types heeft worden die gebruikt.
![Image](https://github.com/user-attachments/assets/4b64cc90-a56b-442d-ad66-ea2cb05c6eb5)
