### ISSUE TITLE
Inrichten repo (admin/branch protection e.d.) submissionstorage

### ISSUE THREAD

**Issue by joostvanderborg** [GemeenteNijmegen/webformulieren-submissionstorage#4]
Deze is nieuw: https://github.com/GemeenteNijmegen/webformulieren-submissionstorage 
Martijn moet admin worden, en branch protection e.d. moet ingericht. Marnix moet mogelijk nog wat doen in de GitHub-monitoring (of dat toelichten :)).

Is hier een readme o.i.d. voor?

**Comment by MartijnvDijk** [comment]
branch protection rule is geset. Kan alleen niet de 'build' and 'pr approvel' actions selecteren. Geen idee waarom, probeer het later opnieuw. Voor nu is er in ieder geval goedkeuring van min 1 persoon nodig.

**Comment by marnixdessing** [comment]
Repository is toegevoegd aan de github-automation checklist
